<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="tools\**" />
        <None Remove="tools\**" />
    </ItemGroup>

    <ItemGroup>
      <None Include="src\player\skills\TeamTeleport.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CounterStrikeSharp.API" Version="1.0.371" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

	<ItemGroup>
		<Reference Include="RayTraceApi">
			<HintPath>libs/RayTraceApi.dll</HintPath>
		</Reference>
	</ItemGroup>

	<!-- Relative path to the WASDMenuAPI source code -->
    <ItemGroup>
        <ProjectReference Include="..\WASDMenuAPI - SRC Files\WASDMenuAPI.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Properties\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Properties\Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

    <PropertyGroup>
        <SourceLangDir>$(MSBuildProjectDirectory)\src\lang</SourceLangDir>
        <ServerLangDir>$(MSBuildProjectDirectory)\..\HeroShift - Server Files\plugins\HeroShift\languages</ServerLangDir>
        <SourceDLL>$(MSBuildProjectDirectory)\bin\$(Configuration)\$(TargetFramework)</SourceDLL>
        <ServerDLL>$(MSBuildProjectDirectory)\..\HeroShift - Server Files\plugins\HeroShift</ServerDLL>
        <SourceGamedataDir>$(MSBuildProjectDirectory)\src\gamedata</SourceGamedataDir>
		<ServerGamedataDir>$(MSBuildProjectDirectory)\..\HeroShift - Server Files\gamedata</ServerGamedataDir>
    </PropertyGroup>

    <!-- Copy language files to server directory -->
    <Target Name="CopyLangFilesToServer" AfterTargets="Build">
        <Message Text="Copying language files from $(SourceLangDir) to $(ServerLangDir)" Importance="High" />
        <ItemGroup>
            <LangFiles Include="$(SourceLangDir)\**\*.*" />
        </ItemGroup>
        <MakeDir Directories="$(ServerLangDir)" Condition="!Exists('$(ServerLangDir)')" />
        <Copy SourceFiles="@(LangFiles)" DestinationFiles="@(LangFiles->'$(ServerLangDir)\\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="false" />
    </Target>

    <!-- Copy compiled DLL to server directory -->
    <Target Name="CopyDLLToServer" AfterTargets="Build">
        <Message Text="Copying compiled DLL from $(SourceDLL) to $(ServerDLL)" Importance="High" />
        <ItemGroup>
            <CompiledDLL Include="$(SourceDLL)\HeroShift.dll" />
            <CompiledDLL Include="$(SourceDLL)\HeroShift.pdb" />
            <CompiledDLL Include="$(SourceDLL)\WASDMenuAPI.dll" />
            <CompiledDLL Include="$(SourceDLL)\WASDMenuAPI.pdb" />
	        <CompiledDLL Include="$(SourceDLL)\Newtonsoft.Json.dll" />
        </ItemGroup>
        <MakeDir Directories="$(ServerDLL)" Condition="!Exists('$(ServerDLL)')" />
        <Copy SourceFiles="@(CompiledDLL)" DestinationFiles="@(CompiledDLL->'$(ServerDLL)\\%(Filename)%(Extension)')" SkipUnchangedFiles="false" />
    </Target>

	<!-- Copy gamedata files to server directory -->
	<Target Name="CopyGamedataFilesToServer" AfterTargets="Build">
		<Message Text="Copying gamedata files from $(SourceGamedataDir) to $(ServerGamedataDir)" Importance="High" />
		<ItemGroup>
			<GamedataFiles Include="$(SourceGamedataDir)\**\*.*" />
		</ItemGroup>
		<MakeDir Directories="$(ServerGamedataDir)" Condition="!Exists('$(ServerGamedataDir)')" />
		<Copy SourceFiles="@(GamedataFiles)" DestinationFiles="@(GamedataFiles->'$(ServerGamedataDir)\\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="false" />
	</Target>
</Project>
